config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'about' => 'home#about'
  devise_for :users
  resources :books
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :opinion, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  # 自己紹介文は50文字以内
  validates :introduction, length: {maximum: 50}
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	# ログインしていない場合の画面制御
	# before_action :authenticate_user!

	def after_sign_in_path_for(resource)
		# ログイン後、マイページへ遷移
		user_path(current_user.id)
	end

	def after_sign_up_path_for(resouce)
		# サインアップ後のメッセージ
		flash[:notice] = "Welcome! You have signed up successfully."
	end

	def after_sign_out_path_for(resource)
		# サインアウト後、トップページへ遷移
		root_path
	end


	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, only: [:edit, :update]

	def index
		@books = Book.all
		@book = Book.new
		@user = current_user
	end

	# 投稿データの保存
	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = 'Book was successfully created.'
			# Book詳細ページへ
			redirect_to book_path(@book.id)
		else
			@user = current_user
			@books = Book.all
			render :index
		end
	end

	# Book詳細ページ
	def show
		@book = Book.new
		@books = Book.find(params[:id])
		@user = User.find(@books.user_id)
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		# book_paramsを追加してエラー回避
		if @book.update(book_params)
			flash[:notice] = 'Book was successfully update.'
			# Book詳細ページへ
			redirect_to book_path(@book.id)
		else
			render :edit
		end
	end

	def destroy
		book = Book.find(params[:id])
		if book.destroy
			flash[:notice] = 'Book was successfully destroyed.'
			# Books一覧ページへリダイレクト
			redirect_to books_path
		end
	end

	private

	def book_params
		params.require(:book).permit(:title, :opinion)
	end

	def ensure_correct_user
		book = Book.find(params[:id])
		user = User.find(book.user_id)
		if user != current_user
			redirect_to root_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # 正しいユーザーかを確かめる
  before_action :ensure_correct_user, only: [:edit, :update]

  # ユーザー一覧
  def index
    @users = User.all
    @user = current_user
    # 空のビューを作成
    @book = Book.new
  end

  # マイページ
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    # マイページに自分の投稿のみを表示
    # @books = @user.books
  end

  # ユーザー編集ページ
  def edit
  	@user = User.find(params[:id])
  end

  # ユーザー情報更新
  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'User info was successfully update.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :opinion)
  end

  def ensure_correct_user
    user = User.find(params[:id])
    if user != current_user
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<!--- Book編集ページ --->
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <h2>Editing Book</h2>
            <% if @book.errors.any? %>
            <div id="error_explanation">
                <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
            <% end %>

            <%= form_for(@book) do |f| %>
            <div class="book_edit_form">
                <label for="">Title</label>
                <%= f.text_field :title, class: "book_title form-control" %>
                <label for="">Opinion</label>
                <%= f.text_area :opinion, class: "book_body form-control" %><br>
                <%= f.submit "Update Book", class: "btn btn-primary btn-block" %>
            </div>
            <% end %>
            <!--- show => book詳細ページへ遷移、back => book一覧ページへ遷移 --->
            <%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %> | <%= link_to "Back", books_path, class: "back" %>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<!--- Book一覧 --->
<div class="container">
    <div class="row">
        <% if @book.errors.any? %>
            <div id="error_explanation">
                <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div class="col-xs-3">
            <!--- @user = current_user  @book = Book.new --->
            <%= render 'users/list', user: @user, book: @book %>
        </div>

        <div class="col-xs-9">
            <h2>Books</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                    </tr>
                </thead>

                <!--- @books = Book.all --->
                <% @books.each do |book| %>
                <tbody>
                    <tr>
                        <td><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "no_image" %></td>
                        <!--- Book詳細ページへ遷移 --->
                        <td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
                        <td><%= book.opinion %></td>
                    </tr>
                </tbody>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<!--- Book詳細ページ --->
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= render 'users/list', user: @user, book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>
			<table class="table">
				<tr>
					<td><%= attachment_image_tag @books.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "no_image" %></td>
					<td><%= @books.title %></td>
					<td><%= @books.opinion %></td>

					<% if @books.user == current_user %>
					<td><%= link_to "Edit", edit_book_path(@books), class: "edit_book_#{@books.id} btn btn-success" %></td>
					<td><%= link_to "Destroy", book_path(@books), class: "destroy_book_#{@books.id} btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
					<% end %>
				</tr>
			</table>
			<!--- ユーザー詳細ページへ戻る --->
			<%= link_to user_path(@books.user_id), class: "user_#{@books.user.id}" do %>
				<%= @user.name %>
			<% end %>

		</div>
	</div>
</div>

app/views/home/about.html.erb
<div class="container">
	<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>
</div>

app/views/home/top.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md-6">
			<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers  !!</h1>
			<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about various books!</p>

			<div class="col-md-11">
				<div class="">
					<%= link_to "Log in", new_user_session_path, class: "sign_in btn btn-info btn-block" %>
				</div>
				<div class="">
					<%= link_to "Sign_up", new_user_registration_path, class: "sign_up btn btn-success btn-block" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>Bookers2</title>
  <meta charset="utf-8">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
  body {
    padding-top: 50px;
  }
  .container {
    margin-right: auto;
    margin-left: auto;
  }
  /* リンクの色をグレーに */
  a {
    color: #666;
  }

  /* トップページのボタン */
  .btn-info {
    color: #666;
  }
  .btn-success {
    color: #666;
  }
  .btn-danger {
    color: #666;
  }
  /* Bookersタイトル */
  .navbar-bland {
    color: #FFF;
  }
  .alert {
    color: green;
    padding-top: 0;
    padding-bottom: 0;
  }
  .field {
    margin-bottom: 10px;
  }
  .actions {
    margin-bottom: 10px;
  }
  /* エラーメッセージを赤字に */
  #error_explanation {
    color: red;
  }
  /* デフォルトのプロフィール画像サイズ */
  .no_image {
    width: 50px;
    height: 50px;
  }
</style>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="nav navbar-nav navbar-left">
        <h4 class="navbar-bland">Bookers</h4>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user.id), class: "home" do %>
          <span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span>
          <% end %>
        </li>
        <li>
          <%= link_to users_path, class: "users" do %>
          <span class="glyphicon glyphicon-user" aria-hidden="true"> Users</span>
          <% end %>
        </li>
        <li>
          <%= link_to books_path, class: "books" do %>
          <span class="glyphicon glyphicon-book" aria-hidden="true"> Books</span>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class: "logout" do%>
          <span class="glyphicon glyphicon-log-out" aria-hidden="true"> logout</span>
          <% end %>
        </li>
        <% else %>
        <li>
          <%= link_to root_path, class: "home" do %>
          <span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span>
          <% end %>
        </li>
        <li>
          <%= link_to "/about", class: "about" do %>
          <span class="glyphicon glyphicon-link" aria-hidden="true"> About</span>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path, class: "sign_up" do %>
          <span class="glyphicon glyphicon-edit" aria-hidden="true"> sign up</span>
          <% end %>
        </li>
        <li>
          <%=link_to new_user_session_path, class: "sign_in" do %>
          <span class="glyphicon glyphicon-log-in" aria-hidden="true"> login</span>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <!--- エラーメッセージ --->
  <div class="container">
    <% if flash[:notice] %>
    <p class="alert alert-notice"><%= notice %></p>
    <% end %>
  </div>
        <%= yield %>

        <footer>
          <div class="container">
            <div class="row">
              <div class="col-md-offset-9 col-md-3">
                <p>CopyRight Infratop.inc</p>
              </div>
            </div>
          </div>
        </footer>

</body>
</html>

app/views/users/_list.html.erb
<div class="container">
	<div class="row">
        <div class="col-xs-3">
            <h2>User info</h2>
            <table class="table">
                <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <tr>
                    <th>name</th><td><%= user.name %></td>
                </tr>
                <tr>
                    <th>introduction</th><td><%= user.introduction %></td>
                </tr>
            </table>

            <!--- ユーザー編集ページへ --->
            <% if user.id = current_user.id %>
                <%=link_to edit_user_path(user), class: "edit_user_#{user.id} btn btn-default btn-block" do %>
                    <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                <% end %>
            <% end %>

            <h2>New book</h2>
            <%= form_for(book) do |f| %>
            <div class="new_book_form">
                <label for="title">Title</label>
                <%= f.text_field :title, class: "book_title form-control" %>
                <label for="opinion">Opinion</label>
                <%= f.text_area :opinion, class: "book_body form-control" %><br>
                <%= f.submit "Create Book", class: "btn btn-primary btn-block" %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<!--- ユーザー編集ページ --->
<div class="container">

	<h2>User info</h2>

	<% if @user.errors.any? %>
	<div id="error_explanation">
		<h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>

		<ul>
			<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<%= form_for(@user) do |f| %>
	<div class="user_edit_form">
		<div class="">
			<label for="name">Name</label>
			<%= f.text_field :name, class: "name" %>
		</div>
		<div class="">
			<label for="image">Image</label>
			<%= f.attachment_field :profile_image, class: "user_image" %>
		</div>
		<div class="">
			<label for="introduction">Introduction</label>
			<%= f.text_area :introduction, class: "introduction" %>
		</div>
		<div class="">
			<%= f.submit "Update User" %>
		</div>
	</div>
	<% end %>
</div>

app/views/users/index.html.erb
<!--- ユーザー一覧ページ --->
<div class="container">
	<div class="row">
        <div class="col-xs-3">
            <!--- @user = current_user  @book = Book.new --->
            <%= render 'users/list', user: @user, book: @book %>
        </div>
        <div class="col-xs-9">
            <h2>Users</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>image</th>
                        <th>name</th>
                    </tr>
                </thead>

                <!--- @users = User.all --->
                <% @users.each do |user| %>
                <tbody>
                    <tr>
                        <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "no_image" %></td>
                        <td><%= user.name %></td>
                        <!--- 各ユーザーのBook一覧ページへ --->
                        <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
                    </tr>
                </tbody>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<!--- マイページ --->
<div class="container">
	<div class="row">
        <div class="col-xs-3">
        	<!--- @user = current_user  @book = Book.new --->
            <%= render 'users/list', user: @user, book: @book %>
        </div>

        <div class ="col-xs-9">
            <h2>Books</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                    </tr>
                </thead>

                <!--- @books = @user.books で自分の投稿のみを表示 --->
                <% @books.each do |book| %>

                <tbody>
                    <tr>
                        <td><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "no_image" %></td>
                        <!--- 自分の投稿の詳細 --->
                        <td><%= link_to book_path(book.id), class: "book_#{book.id}" do %>
                        	<%= book.title %>
                        	<% end %>
                        </td>
                        <td><%= book.opinion %></td>
                    </tr>
                </tbody>
                <% end %>
            </table>
        </div>
    </div>
</div>